-- ============================================================
-- Catálogo de Tipos de Prenda
-- Ejecutar en Supabase SQL Editor
-- 149 referencias: ATP, Conjunto ATP, TC, Conjunto TC, Promocionales
-- ============================================================

CREATE TABLE IF NOT EXISTS telas.catalogo_tipos_prenda (
  id       SERIAL PRIMARY KEY,
  nombre   TEXT    NOT NULL,
  categoria TEXT   NOT NULL,   -- 'ATP' | 'Conjunto ATP' | 'TC' | 'Conjunto TC' | 'Promocionales'
  genero   TEXT,               -- 'Caballero' | 'Dama' | 'Niño' | NULL
  mangas   TEXT,               -- 'Sin Mangas' | 'Manga Corta' | 'Manga Larga' | 'Manga China' | NULL
  medidas  TEXT,               -- para Promocionales
  activo   BOOLEAN NOT NULL DEFAULT true,
  orden    INT     NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_catalogo_tipos_prenda_categoria ON telas.catalogo_tipos_prenda(categoria);
CREATE INDEX IF NOT EXISTS idx_catalogo_tipos_prenda_activo    ON telas.catalogo_tipos_prenda(activo);

GRANT ALL ON telas.catalogo_tipos_prenda TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE telas.catalogo_tipos_prenda_id_seq TO anon, authenticated;

-- ─── ATP (21) ──────────────────────────────────────────────
INSERT INTO telas.catalogo_tipos_prenda (nombre, categoria, genero, mangas, medidas, orden) VALUES
('AERORUN ATP',          'ATP', 'Caballero', 'Sin Mangas',   NULL,  1),
('AERORUN ATP',          'ATP', 'Dama',      'Sin Mangas',   NULL,  2),
('SOCCER ATP',           'ATP', 'Caballero', 'Manga Corta',  NULL,  3),
('RUNNING ATP',          'ATP', 'Caballero', 'Manga Corta',  NULL,  4),
('RUNNING ATP',          'ATP', 'Dama',      'Manga Corta',  NULL,  5),
('CICLISTA ATP',         'ATP', 'Caballero', 'Manga Corta',  NULL,  6),
('CICLISTA ATP',         'ATP', 'Caballero', 'Manga Larga',  NULL,  7),
('CICLISTA BEGINNER',    'ATP', 'Caballero', 'Manga Corta',  NULL,  8),
('FALDA ATP',            'ATP', 'Dama',       NULL,          NULL,  9),
('FITTED ATP',           'ATP', 'Caballero', 'Manga Corta',  NULL, 10),
('FITTED ATP',           'ATP', 'Caballero', 'Manga Larga',  NULL, 11),
('FITTED ATP',           'ATP', 'Dama',      'Manga Corta',  NULL, 12),
('FITTED ATP',           'ATP', 'Dama',      'Manga Larga',  NULL, 13),
('RUNNING TANK ATP',     'ATP', 'Caballero', 'Sin Mangas',   NULL, 14),
('SHORT SOCCER ATP',     'ATP', 'Caballero',  NULL,          NULL, 15),
('SHORT RUNNING ATP',    'ATP', 'Caballero',  NULL,          NULL, 16),
('SHORT RUNNING ATP',    'ATP', 'Dama',       NULL,          NULL, 17),
('CROP TOP',             'ATP', 'Dama',      'Sin Mangas',   NULL, 18),
('TOP ATP',              'ATP', 'Dama',      'Sin Mangas',   NULL, 19),
('ADIDAS STYLE',         'ATP', 'Caballero', 'Manga Corta',  NULL, 20),
('BASKETBALL ATP',       'ATP', 'Caballero', 'Sin Mangas',   NULL, 21),

-- ─── Conjunto ATP (15) ─────────────────────────────────────
('UNIFORME DE FUTBOLL ATP',     'Conjunto ATP', 'Caballero', 'Manga Corta', NULL,  1),
('UNIFORME DE FUTBOLL ATP',     'Conjunto ATP', 'Dama',      'Manga Corta', NULL,  2),
('UNIFORME DE FUTBOLL ATP',     'Conjunto ATP', 'Niño',      'Manga Corta', NULL,  3),
('UNIFORME DE BASKETBALL ATP',  'Conjunto ATP', 'Caballero', 'Manga Corta', NULL,  4),
('UNIFORME DE BASKETBALL ATP',  'Conjunto ATP', 'Dama',      'Manga Corta', NULL,  5),
('UNIFORME DE BASKETBALL ATP',  'Conjunto ATP', 'Niño',      'Manga Corta', NULL,  6),
('CONJUTO DE PRESENTACION ATP', 'Conjunto ATP', 'Caballero', 'Manga Larga', NULL,  7),
('CONJUTO DE PRESENTACION ATP', 'Conjunto ATP', 'Dama',      'Manga Larga', NULL,  8),
('CONJUTO DE PRESENTACION ATP', 'Conjunto ATP', 'Niño',      'Manga Larga', NULL,  9),
('UNIFORME DE FUTBOLL ATP',     'Conjunto ATP', 'Caballero', 'Manga Larga', NULL, 10),
('UNIFORME DE FUTBOLL ATP',     'Conjunto ATP', 'Dama',      'Manga Larga', NULL, 11),
('UNIFORME DE FUTBOLL ATP',     'Conjunto ATP', 'Niño',      'Manga Larga', NULL, 12),
('UNIFORME DE BASKETBALL ATP',  'Conjunto ATP', 'Caballero', 'Manga Larga', NULL, 13),
('UNIFORME DE BASKETBALL ATP',  'Conjunto ATP', 'Dama',      'Manga Larga', NULL, 14),
('UNIFORME DE BASKETBALL ATP',  'Conjunto ATP', 'Niño',      'Manga Larga', NULL, 15),

-- ─── TC (77) ───────────────────────────────────────────────
('AERORUN TC',                 'TC', 'Caballero', 'Sin Mangas',   NULL,  1),
('AERORUN TC',                 'TC', 'Dama',      'Sin Mangas',   NULL,  2),
('BASEBALL TC',                'TC', 'Caballero', 'Manga Corta',  NULL,  3),
('BASICO',                     'TC', 'Caballero', 'Manga Corta',  NULL,  4),
('BASICO',                     'TC', 'Dama',      'Manga Corta',  NULL,  5),
('BASICO',                     'TC', 'Niño',      'Manga Corta',  NULL,  6),
('BASICO',                     'TC', 'Caballero', 'Manga Larga',  NULL,  7),
('BASICO',                     'TC', 'Dama',      'Manga Larga',  NULL,  8),
('BASICO',                     'TC', 'Niño',      'Manga Larga',  NULL,  9),
('BASICO V',                   'TC', 'Caballero', 'Manga Corta',  NULL, 10),
('BASICO V',                   'TC', 'Dama',      'Manga Corta',  NULL, 11),
('BASICO V',                   'TC', 'Niño',      'Manga Corta',  NULL, 12),
('BASICO V',                   'TC', 'Caballero', 'Manga Larga',  NULL, 13),
('BASICO V',                   'TC', 'Dama',      'Manga Larga',  NULL, 14),
('BASICO V',                   'TC', 'Niño',      'Manga Larga',  NULL, 15),
('VOLLEYBALL',                 'TC', 'Dama',      'Manga China',  NULL, 16),
('BASICO SEMITUBLAR',          'TC', 'Caballero', 'Manga Corta',  NULL, 17),
('BASICO SEMITUBLAR',          'TC', 'Caballero', 'Manga Larga',  NULL, 18),
('BASKETBALL TC',              'TC', 'Caballero', 'Sin Mangas',   NULL, 19),
('VOLLEYBALL TC',              'TC', 'Caballero', 'Sin Mangas',   NULL, 20),
('BERMUDAS',                   'TC', 'Caballero',  NULL,          NULL, 21),
('BIKER',                      'TC', 'Dama',       NULL,          NULL, 22),
('BUZO TC',                    'TC', 'Caballero',  NULL,          NULL, 23),
('BUZO KIDS TC',               'TC', 'Niño',       NULL,          NULL, 24),
('CHUMPA',                     'TC', 'Caballero', 'Manga Larga',  NULL, 25),
('CHUMPA',                     'TC', 'Niño',      'Manga Larga',  NULL, 26),
('CHUMPA CON GORRO',           'TC', 'Caballero', 'Manga Larga',  NULL, 27),
('CHUMPA CON GORRO',           'TC', 'Niño',      'Manga Larga',  NULL, 28),
('HOODIE',                     'TC', 'Caballero', 'Manga Larga',  NULL, 29),
('HOODIE',                     'TC', 'Niño',      'Manga Larga',  NULL, 30),
('HOODIE CON CUELLO',          'TC', 'Caballero', 'Manga Larga',  NULL, 31),
('HOODIE CON CUELLO',          'TC', 'Niño',      'Manga Larga',  NULL, 32),
('HOODIE CON CUELLO Y ZIPPER', 'TC', 'Caballero', 'Manga Larga',  NULL, 33),
('HOODIE CON CUELLO Y ZIPPER', 'TC', 'Niño',      'Manga Larga',  NULL, 34),
('COLUMBIA',                   'TC', 'Caballero', 'Manga Corta',  NULL, 35),
('COLUMBIA',                   'TC', 'Dama',      'Manga Corta',  NULL, 36),
('COLUMBIA',                   'TC', 'Caballero', 'Manga Larga',  NULL, 37),
('COLUMBIA',                   'TC', 'Dama',      'Manga Larga',  NULL, 38),
('CROP TC',                    'TC', 'Dama',      'Sin Mangas',   NULL, 39),
('BASICO CON PUÑO',            'TC', 'Caballero', 'Manga Larga',  NULL, 40),
('BASICO CON PUÑO',            'TC', 'Dama',      'Manga Larga',  NULL, 41),
('BASICO CON PUÑO',            'TC', 'Niño',      'Manga Larga',  NULL, 42),
('BASICO RANGLAN',             'TC', 'Caballero', 'Manga Corta',  NULL, 43),
('BASICO RANGLAN',             'TC', 'Dama',      'Manga Corta',  NULL, 44),
('BASICO RANGLAN',             'TC', 'Niño',      'Manga Corta',  NULL, 45),
('BASICO RANGLAN',             'TC', 'Caballero', 'Manga Larga',  NULL, 46),
('BASICO RANGLAN',             'TC', 'Dama',      'Manga Larga',  NULL, 47),
('BASICO RANGLAN',             'TC', 'Niño',      'Manga Larga',  NULL, 48),
('BASICO RANGLAN V',           'TC', 'Caballero', 'Manga Corta',  NULL, 49),
('BASICO RANGLAN V',           'TC', 'Dama',      'Manga Corta',  NULL, 50),
('BASICO RANGLAN V',           'TC', 'Niño',      'Manga Corta',  NULL, 51),
('BASICO RANGLAN V',           'TC', 'Caballero', 'Manga Larga',  NULL, 52),
('BASICO RANGLAN V',           'TC', 'Dama',      'Manga Larga',  NULL, 53),
('BASICO RANGLAN V',           'TC', 'Niño',      'Manga Larga',  NULL, 54),
('POLO',                       'TC', 'Caballero', 'Manga Corta',  NULL, 55),
('POLO',                       'TC', 'Dama',      'Manga Corta',  NULL, 56),
('POLO',                       'TC', 'Niño',      'Manga Corta',  NULL, 57),
('POLO PLAQUETA VISTA',        'TC', 'Caballero', 'Manga Corta',  NULL, 58),
('POLO PLAQUETA VISTA',        'TC', 'Dama',      'Manga Corta',  NULL, 59),
('POLO PLAQUETA VISTA',        'TC', 'Niño',      'Manga Corta',  NULL, 60),
('POLO CON RIB',               'TC', 'Caballero', 'Manga Corta',  NULL, 61),
('POLO CON RIB',               'TC', 'Dama',      'Manga Corta',  NULL, 62),
('POLO CON RIB',               'TC', 'Niño',      'Manga Corta',  NULL, 63),
('POLO CON RIN Y PUÑO',        'TC', 'Caballero', 'Manga Corta',  NULL, 64),
('POLO CON RIN Y PUÑO',        'TC', 'Dama',      'Manga Corta',  NULL, 65),
('POLO CON RIN Y PUÑO',        'TC', 'Niño',      'Manga Corta',  NULL, 66),
('SHORT FUTBOL',               'TC', 'Caballero',  NULL,          NULL, 67),
('SHORT FUTBOL',               'TC', 'Niño',       NULL,          NULL, 68),
('SHORT BASKETBALL',           'TC', 'Caballero',  NULL,          NULL, 69),
('SHORT BASKETBALL',           'TC', 'Niño',       NULL,          NULL, 70),
('SHORT ESPECIAL',             'TC', 'Dama',       NULL,          NULL, 71),
('SOCIAL',                     'TC', 'Caballero', 'Manga Corta',  NULL, 72),
('SOCIAL',                     'TC', 'Dama',      'Manga Corta',  NULL, 73),
('SOCIAL',                     'TC', 'Caballero', 'Manga Larga',  NULL, 74),
('SOCIAL',                     'TC', 'Dama',      'Manga Larga',  NULL, 75),
('OXFORD',                     'TC', 'Caballero', 'Manga Corta',  NULL, 76),
('OXFORD',                     'TC', 'Caballero', 'Manga Larga',  NULL, 77),

-- ─── Conjunto TC (19) ──────────────────────────────────────
('UNIFORME DE FUTBOLL',     'Conjunto TC', 'Caballero', 'Manga Corta', NULL,  1),
('UNIFORME DE FUTBOLL',     'Conjunto TC', 'Dama',      'Manga Corta', NULL,  2),
('UNIFORME DE FUTBOLL',     'Conjunto TC', 'Niño',      'Manga Corta', NULL,  3),
('UNIFORME DE BASKETBALL',  'Conjunto TC', 'Caballero', 'Manga Corta', NULL,  4),
('UNIFORME DE BASKETBALL',  'Conjunto TC', 'Dama',      'Manga Corta', NULL,  5),
('UNIFORME DE BASKETBALL',  'Conjunto TC', 'Niño',      'Manga Corta', NULL,  6),
('CONJUTO DE PRESENTACION', 'Conjunto TC', 'Caballero', 'Manga Larga', NULL,  7),
('CONJUTO DE PRESENTACION', 'Conjunto TC', 'Dama',      'Manga Larga', NULL,  8),
('CONJUTO DE PRESENTACION', 'Conjunto TC', 'Niño',      'Manga Larga', NULL,  9),
('UNIFORME DE FUTBOLL',     'Conjunto TC', 'Caballero', 'Manga Larga', NULL, 10),
('UNIFORME DE FUTBOLL',     'Conjunto TC', 'Dama',      'Manga Larga', NULL, 11),
('UNIFORME DE FUTBOLL',     'Conjunto TC', 'Niño',      'Manga Larga', NULL, 12),
('UNIFORME DE BASKETBALL',  'Conjunto TC', 'Caballero', 'Manga Larga', NULL, 13),
('UNIFORME DE BASKETBALL',  'Conjunto TC', 'Dama',      'Manga Larga', NULL, 14),
('UNIFORME DE BASKETBALL',  'Conjunto TC', 'Niño',      'Manga Larga', NULL, 15),
('PIJAMA',                  'Conjunto TC', 'Caballero', 'Manga Larga', NULL, 16),
('PIJAMA',                  'Conjunto TC', 'Dama',      'Manga Larga', NULL, 17),
('PIJAMA',                  'Conjunto TC', 'Niño',      'Manga Larga', NULL, 18),
('UNIFORME MIXTO',          'Conjunto TC', 'Caballero',  NULL,         NULL, 19),

-- ─── Promocionales (17) ────────────────────────────────────
('MANTEL',               'Promocionales', NULL, NULL, '70X30"',  1),
('BACKDROP',             'Promocionales', NULL, NULL, '90X90"',  2),
('BANNER ARAÑA',         'Promocionales', NULL, NULL, '60X30',   3),
('FLYBANNER GOTA',       'Promocionales', NULL, NULL, '1.8 m',   4),
('FLYBANNER VELA',       'Promocionales', NULL, NULL, '1.8 m',   5),
('BANDANA',              'Promocionales', NULL, NULL,  NULL,     6),
('BINCHA',               'Promocionales', NULL, NULL,  NULL,     7),
('MANGAS DE PROTECCION', 'Promocionales', NULL, NULL, 'XS y S', 8),
('TOALLA',               'Promocionales', NULL, NULL, '58X36"',  9),
('TOALLA DE MANO',       'Promocionales', NULL, NULL, '18X19"', 10),
('BANDERA',              'Promocionales', NULL, NULL, '58X36"', 11),
('DELANTAL',             'Promocionales', NULL, NULL,  NULL,    12),
('MANDIL',               'Promocionales', NULL, NULL,  NULL,    13),
('CINTA',                'Promocionales', NULL, NULL, '3"',     14),
('ESTOLA',               'Promocionales', NULL, NULL, '58X5"',  15),
('YARDAJE',              'Promocionales', NULL, NULL,  NULL,    16),
('CORTINA',              'Promocionales', NULL, NULL,  NULL,    17);

-- Verificación: SELECT categoria, COUNT(*) FROM telas.catalogo_tipos_prenda GROUP BY categoria ORDER BY categoria;
-- Total esperado: 149 filas
