-- =====================================================================
-- Comunicaciones Internas — FASE 5 (Generación de tareas)
-- ---------------------------------------------------------------------
-- Convierte una instrucción del chat en una tarea formal con responsable(s),
-- plazo, tipo de entregable, estados e historial. Una tarea puede tener
-- varios responsables (un registro por responsable).
-- Ejecutar en el SQL Editor de Supabase (después de las fases anteriores).
-- =====================================================================

create table if not exists telas.chat_tareas (
  id uuid primary key default gen_random_uuid(),
  consecutivo bigint generated by default as identity,
  conversacion_id uuid references telas.chat_conversaciones(id) on delete cascade,
  mensaje_origen_id uuid references telas.chat_mensajes(id) on delete set null,
  titulo text not null,
  descripcion text,
  prioridad text default 'media',           -- alta | media | baja
  tipo_entregable text default 'confirmacion', -- archivo | texto | imagen | confirmacion
  fecha_entrega date,
  creado_por text,
  created_at timestamptz default now()
);

create index if not exists chat_tareas_conv_idx on telas.chat_tareas (conversacion_id);
create index if not exists chat_tareas_creador_idx on telas.chat_tareas (creado_por);

-- Un registro por responsable (asignación individual).
create table if not exists telas.chat_tarea_responsables (
  id uuid primary key default gen_random_uuid(),
  tarea_id uuid not null references telas.chat_tareas(id) on delete cascade,
  usuario_email text not null,
  estado text default 'pendiente',          -- pendiente | en_proceso | entregada | aceptada | devuelta | vencida
  entregable_texto text,
  entregable_url text,
  entregable_nombre text,
  fecha_entregable timestamptz,
  observaciones text,                        -- observaciones de devolución
  updated_at timestamptz default now(),
  unique (tarea_id, usuario_email)
);

create index if not exists chat_tarea_resp_tarea_idx on telas.chat_tarea_responsables (tarea_id);
create index if not exists chat_tarea_resp_usuario_idx on telas.chat_tarea_responsables (usuario_email, estado);

-- Historial completo de la tarea (creación, cambios de estado, entregables, observaciones).
create table if not exists telas.chat_tarea_eventos (
  id uuid primary key default gen_random_uuid(),
  tarea_id uuid not null references telas.chat_tareas(id) on delete cascade,
  responsable_email text,
  tipo text,                                 -- creada | estado | entregable | observacion
  detalle text,
  usuario text,                              -- actor
  created_at timestamptz default now()
);

create index if not exists chat_tarea_eventos_tarea_idx on telas.chat_tarea_eventos (tarea_id, created_at);

grant select, insert, update, delete on telas.chat_tareas to anon, authenticated, service_role;
grant select, insert, update, delete on telas.chat_tarea_responsables to anon, authenticated, service_role;
grant select, insert, update, delete on telas.chat_tarea_eventos to anon, authenticated, service_role;

-- Realtime (opcional; útil para reflejar cambios de estado en vivo).
do $$
begin
  begin alter publication supabase_realtime add table telas.chat_tareas; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table telas.chat_tarea_responsables; exception when duplicate_object then null; end;
end $$;
